#%RAML 1.0 NamedExample
zipcode:
  {
    "item": {
        "ID": "21632",
        "CountiesArea": "311",
        "ZipCodePopulation": "978",
        "HouseholdsPerZipcode": "397.0000",
        "WhitePop": "946",
        "BlackPop": "23",
        "HispanicPop": "8",
        "AsianPop": "4",
        "IndianPop": "8",
        "HawaiianPop": "3",
        "OtherPop": "3",
        "MalePop": "492",
        "FemalePop": "486",
        "PersonsPerHousehold": "2.46",
        "AverageHouseValue": "220800.00",
        "IncomePerHousehold": "59342.00",
        "MedianAge": "46.00",
        "MedianAgeMale": "46.90",
        "MedianAgeFemale": "45.50",
        "AverageFamilySize": "2.95",
        "Bus03Establishments": "8",
        "Bus03Employment": "15",
        "Bus03PayrollQuarter1": "113",
        "Bus03PayrollAnnual": "496",
        "Bus03EmploymentFlag": " ",
        "CBSAPop2003": null,
        "CBSADivPop2003": "0",
        "DeliveryActive": "506",
        "DeliveryBusiness": "5",
        "DeliveryResidential": "493",
        "DeliverySpecial": "493",
        "DeliveryBox": "0",
        "DeliverySFDU": "475",
        "DeliveryMFDU": "0",
        "PopulationEstimate": "1212",
        "_109thDistrict": "0",
        "_109thArea": "0",
        "_110thDistrict": "06",
        "_110thArea": "5930.02",
        "GrowthRank": "0",
        "GrowthHousingUnits2003": "0",
        "GrowthHousingUnits2004": "0",
        "GrowthIncreaseNumber": "0",
        "GrowthIncreasePercentage": "0.00",
        "Latitude": "38.759252",
        "Longitude": "-78.361510",
        "Elevation": "1105.00",
        "AreaLand": "29.379000",
        "AreaWater": "0.025000",
        "Primary": "P",
        "State": "VA",
        "CityType": "P",
        "CityAliasType": null,
        "Classification": " ",
        "ZipCode": "22650",
        "CityAliasAbbr": null,
        "AreaCode": "540",
        "AreaCodeTemp": "540",
        "AreaCodeTest": null,
        "City": "RILEYVILLE",
        "CityAliasName": "RILEYVILLE",
        "CountyName": "PAGE",
        "CountyFIPS": "139",
        "StateFIPS": "51",
        "CountyANSI": "139",
        "StateANSI": "51",
        "TimeZone": "5",
        "DayLightSaving": "Y",
        "MSA": null,
        "PMSA": null,
        "PMSAName": null,
        "CSA": null,
        "CSAName": null,
        "CBSA": null,
        "CBSA_DIV": null,
        "CBSA_DIV_Name": null,
        "CBSA_Type": null,
        "CBSA_Name": null,
        "MSAName": null,
        "Region": "South",
        "Division": "South Atlantic",
        "MailingName": "Y",
        "MultiCounty": " ",
        "Prev": "22649",
        "Next": "22652",
        "CityStateKey": "X27535",
        "PreferredLastLineKey": "X27535",
        "PreferredLastLineName": "RILEYVILLE",
        "IntroDateZIP": "<2004-10",
        "IntroDateAlias": "<2004-10",
        "FacilityCode": "P",
        "CityDeliveryIndicator": "N",
        "CarrierRouteRateSortation": "C",
        "FinanceNumber": "517662",
        "UniqueZIPName": null,
        "MixedCaseCity": "Rileyville",
        "MixedCaseAlias": "Rileyville",
        "SSA_State_County_Code": "49690",
        "Medicare_CBSA_Code": "99949",
        "Medicare_CBSA_Name": "Rural Areas in VA",
        "Medicare_CBSA_Type": "Micro",
        "Medicare_Rating_Area_ID": "12",
        "StateFullName": "Virginia",
        "CountyMixedCase": null
    }
}