http:
 host:"0.0.0.0";
 port:"8081"

db:
  host: "db.icraftsoft.net"
  port: "3306"
  user: "craft_trainer"
  password: "Cr@fTTraNinGp@ssw0Rd2023"
  database: "craft_training"
shophify:
  username: "fcdbdd9ae6ab70463ab5d219ef48265d"
  password: "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"
weather:
  host: "api.openweathermap.org"
L1project:
  host: "api.zip-codes.com"
  port: "443"
numberverify:
   host: "apilayer.net"